spring:
  data:
    mongodb:
      host: "127.0.0.1"
    rest:
      base-path: "/api"
web3j:
  client-address: "https://ropsten.infura.io"
  network-id: "3"
  http-timeout-seconds: 60
caragent:
  ethereum:
    wallet-password: "password"

